const admin = require('firebase-admin');
const serviceAccount = require('./serviceAccountKey.json');

admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();

const courses = [
    {
        category: "Programming",
        description: "Java Programming for Beginners",
        difficulty: "Beginner",
        duration: "4hrs",
        image: "https://www.simplilearn.com/ice9/app/C-Programming-Basics-Kick-start-your-programming-career.jpg",
        provider: "Simplilearn",
        title: "Java Programming for Beginners",
        url: "https://www.simplilearn.com/free-java-beginners-course-skillup?tag=programming",
    },
    {
        category: "Programming",
        description: "Object-Oriented Programming in Java Programming",
        difficulty: "Intermediate",
        duration: "2hrs",
        image: "https://www.simplilearn.com/ice9/app/OOPs-in-Java-Programming.jpg",
        provider: "Simplilearn",
        title: "OOPs in Java Programming",
        url: "https://www.simplilearn.com/free-java-object-oriented-programming-course-skillup?tag=programming",
    },
    {
        category: "Programming",
        description: "Java Spring Framework fundamentals",
        difficulty: "Intermediate",
        duration: "3hrs",
        image: "https://cdn01.alison-static.net/courses/5664/alison_courseware_intro_5664.jpg",
        provider: "simplilearn",
        title: "Inroduction to Java Spring Framework",
        url: "https://www.simplilearn.com/introduction-to-java-spring-framework-fundamentals-skillup?tag=java%20programming",
    },
    {
        category: "Programming",
        description: "Advanced Swift Programming for IOS",
        difficulty: "Advanced",
        duration: "4hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/1640/alison_courseware_intro_1640.jpg",
        provider: "Alison",
        title: "Beginner in Advanced Swift Programming for IOS",
        url: "https://alison.com/course/introduction-to-advanced-swift-programming-for-ios",
    },
    {
        category: "Programming",
        description: "Dart Programming for App Development",
        difficulty: "Advanced",
        duration: "3hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/4407/alison_courseware_intro_4407.jpg",
        provider: "Alison",
        title: "App Development using Dart Programming language", 
        url: "https://alison.com/course/app-development-using-dart-programming-language",
    },
    {
        category: "Programming",
        description: "Master PLC Programming",
        difficulty: "Advanced",
        duration: "6hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/3691/alison_courseware_intro_3691.jpg",
        provider: "Alison",
        title: "Master PLC Programming", 
        url: "https://alison.com/course/master-plc-programming",
    },
    {
        category: "Data Science",
        description: "Python Programming for Data Science",
        difficulty: "Beginner",
        duration: "10hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/8d7a49ae4457_w240.webp",
        provider: "University of California San Diego via edx",
        title: "Python for Data Science", 
        url: "https://www.classcentral.com/course/python-the-university-of-california-san-diego-pyt-8209",
    },
    {
        category: "Data Science",
        description: "Basic Tools for Data Science",
        difficulty: "Beginner",
        duration: "17hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/ea23eee2761e_w240.webp",
        provider: "John Hopkins University via Coursera",
        title: "The Data Scientist’s Toolbox",   
        url: "https://www.classcentral.com/course/datascitoolbox-1712",
    },
    {
        category: "Data Science",
        description: "Basic ways data can be obtained",
        difficulty: "Intermediate",
        duration: "20hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/7841679b4121_w240.webp",
        provider: "John Hopkins University via Coursera",
        title: "Getting and Cleaning Data",   
        url: "https://www.classcentral.com/course/getdata-1714",
    },
    {
        category: "Data Science",
        description: "Mastering Data Analysis",
        difficulty: "Intermediate",
        duration: "23hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/9fc1c330ac95_w480.webp",
        provider: "Duke University via Coursera",
        title: "Mastering Data Analysis in Excel",   
        url: "https://www.classcentral.com/course/analytics-excel-4310",
    },
    {
        category: "Data Science",
        description: "Data Science in Real Life",
        difficulty: "Intermediate",
        duration: "7hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/cac2c3439ff0_w480.webp",
        provider: "John Hopkins University via Coursera",
        title: "Data Science in Real Life",   
        url: "https://www.classcentral.com/course/real-life-data-science-4389",
    },
    {
        category: "Data Science",
        description: "Capstone project class",
        difficulty: "Advanced",
        duration: "6hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/c1259f840ecd_w240.webp",
        provider: "John Hopkins University via Coursera",
        title: "Data Science capstone",   
        url: "https://www.classcentral.com/course/data-science-project-2791",
    },
    {
        category: "Data Science",
        description: "Apply data analytics techniques for real world socital problems",
        difficulty: "Advanced",
        duration: "8hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/50e03e6cec85_w480.webp",
        provider: "Weseleyan University via Coursera",
        title: "Data Analysis and Interpretation capstone",   
        url: "https://www.classcentral.com/course/data-analysis-capstone-5110",
    },
    {
        category: "Data Science",
        description: "Data Science with scala",
        difficulty: "Advanced",
        duration: "6hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/0f8c37abe4af_w480.webp",
        provider: "Cognitive Class",
        title: "Data Science with Scala",   
        url: "https://www.classcentral.com/course/cognitive-class-data-science-with-scala-118529",
    },
    {
        category: "Computer Graphics",
        description: "Rendering and GRaphics basics",
        difficulty: "Beginner",
        duration: "3hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/8e7a0fb2d56a_w240.webp",
        provider: "Class Central",
        title: "Rendering and graphics",   
        url: "https://www.classcentral.com/classroom/youtube-rendering-graphics-90462",
    },
    {
        category: "Computer Graphics",
        description: "User Interfanc and User Experience basics",
        difficulty: "Beginner",
        duration: "1hr",
        imageUrl: "https://www.simplilearn.com/ice9/app/amongus_1.jpg",
        provider: "Simplilearn",
        title: "UI/UX basics",   
        url: "https://www.simplilearn.com/free-graphic-design-beginner-course-skillup?tag=graphics",
    },
    {
        category: "Computer Graphics",
        description: "one-stop solution for creating a C# GUI",
        difficulty: "Beginner",
        duration: "6hrs",
        imageUrl: "https://i.ytimg.com/vi/UMc1HLyBHSQ/hqdefault.jpg",
        provider: "Simplilearn",
        title: "C# GUI",   
        url: "https://www.simplilearn.com/tutorials/c-sharp-tutorial/c-sharp-gui?tag=graphics",
    },
    {
        category: "Computer Graphics",
        description: "Build a modern UI using Chakara UI",
        difficulty: "Intermediate",
        duration: "43mins",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/854147438e71_w480.webp",
        provider: "Class Central",
        title: "Build a modern UI using Chakara UI",   
        url: "https://www.classcentral.com/course/egghead-io-build-a-modern-user-interface-with-chakra-ui-118425",
    },
    {
        category: "Computer Graphics",
        description: "Graphics Design",
        difficulty: "Intermediate",
        duration: "30hrs",
        imageUrl: "https://i.ytimg.com/vi/UMc1HLyBHSQ/hqdefault.jpg",
        provider: "Udemy",
        title: "Graphics Design Master Class",   
        url: "https://www.udemy.com/course/graphic-design-masterclass-everything-you-need-to-know/?couponCode=ST3MT200225A",
    },
    {
        category: "Computer Graphics",
        description: "User Experience Design Essentials - Adobe XD UI UX Design",
        difficulty: "Intermediate",
        duration: "10hrs",
        imageUrl: "https://i.ytimg.com/vi/UMc1HLyBHSQ/hqdefault.jpg",
        provider: "Udemi",
        title: "User Experience Design Essentials",   
        url: "https://www.udemy.com/course/ui-ux-web-design-using-adobe-xd/?couponCode=ST3MT200225A",
    },
    {
        category: "Computer Graphics",
        description: "Creating accessible website",
        difficulty: "Advanced",
        duration: "3hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/2966/alison_courseware_intro_2966.jpg",
        provider: "Alison",
        title: "Web Accessibility Development",   
        url: "https://alison.com/course/web-accessibility-development",
    },
    {
        category: "Computer Graphics",
        description: "A complete guide to User Experience Design",
        difficulty: "Advanced",
        duration: "3hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/3994/alison_courseware_intro_3994.jpg",
        provider: "Alison",
        title: "User Experience Design",   
        url: "https://alison.com/course/a-complete-guide-to-user-experience-design",
    },
    {
        category: "Computer Graphics",
        description: "UX interviews",
        difficulty: "Advanced",
        duration: "3hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/3965/alison_courseware_intro_3965.jpg",
        provider: "Alison",
        title: "Nailing UX Interviews and Creating a Viable UX Design Career",   
        url: "https://alison.com/course/nailing-ux-interviews-and-creating-a-viable-ux-design-career",
    },
    {
        category: "Web Development",
        description: "WordPress Fundamentals - Content Management System",
        difficulty: "Beginner",
        duration: "3hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/4478/alison_courseware_intro_4478.jpg",
        provider: "Alison",
        title: "WordPress Fundamentals - Content Management System",   
        url: "https://alison.com/course/wordpress-fundamentals-content-management-system-cms",
    },
    {
        category: "Web Development",
        description: "Responsive Website with HTML, CSS, and Javascript",
        difficulty: "Beginner",
        duration: "23hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/ef2c7a3f8262_w480.webp",
        provider: "Class Central",
        title: "Responsive Website basics",   
        url: "https://www.classcentral.com/course/website-coding-4191",
    },
    {
        category: "Web Development",
        description: "Full Stack Development",
        difficulty: "Intermediate",
        duration: "7hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/a701108cded6_w480.webp",
        provider: "Class Central",
        title: "Full Stack for Frontend Engineers",   
        url: "https://www.classcentral.com/course/frontend-masters-full-stack-for-front-end-engineers-v2-118021",
    },
    {
        category: "Web Development",
        description: "ASP.NET core",
        difficulty: "Intermediate",
        duration: "6hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/3342/alison_courseware_intro_3342.jpg",
        provider: "Alison",
        title: "Exploring ASP.NET core",   
        url: "https://alison.com/course/exploring-asp-net-core-intermediate",
    },
    {
        category: "Web Development",
        description: "Laravel Advanced Topics",
        difficulty: "Intermediate",
        duration: "6hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/7039/alison_courseware_intro_7039.jpg",
        provider: "Alison",
        title: "Laravel Advanced",   
        url: "https://alison.com/course/laravel-advanced-topics",
    },
    {
        category: "Web Development",
        description: "Modern React with Redux",
        difficulty: "Advanced",
        duration: "75hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/7039/alison_courseware_intro_7039.jpg",
        provider: "Udemi",
        title: "Modern React with Redux",   
        url: "https://www.udemy.com/course/react-redux/?couponCode=ST3MT200225A",
    },
    {
        category: "Web Development",
        description: "Web Accessibility",
        difficulty: "Advanced",
        duration: "10hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/2967/alison_courseware_intro_2967.jpg",
        provider: "Alison",
        title: "Web Accessibility",   
        url: "https://alison.com/course/diploma-in-web-accessibility",
    },
    {
        category: "Web Development",
        description: "Web Development with jQUery, AJAX, and JSON",
        difficulty: "Advanced",
        duration: "4hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/4918/alison_courseware_intro_4918.jpg",
        provider: "Alison",
        title: "Web Development with jQUery, AJAX, and JSON",   
        url: "https://alison.com/course/web-development-with-jquery-ajax-and-json",
    },
    {
        category: "Computer Security",
        description: "Basics of Security Management",
        difficulty: "Beginner",
        duration: "3hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/5689/alison_courseware_intro_5689.jpg",
        provider: "Alison",
        title: "Basics of Security Management",   
        url: "https://alison.com/course/basics-of-security-management",
    },
    {
        category: "Computer Security",
        description: "Introduction to cyber security",
        difficulty: "Beginner",
        duration: "12weeks",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image/69fb745426f2.jpg",
        provider: "Class Central",
        title: "Introduction to cyber security",   
        url: "https://www.classcentral.com/course/swayam-introduction-to-cyber-security-14116",
    },
    {
        category: "Computer Security",
        description: "Codes and Secrets: Fundamentals of Computer Security - A Public Engagement Lecture",
        difficulty: "Beginner",
        duration: "2hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/195fa100f2c0_w240.webp",
        provider: "Class Central",
        title: "Fundamentals of computer security",   
        url: "https://www.classcentral.com/classroom/youtube-codes-and-secrets-a-public-engagement-event-hd-139301",
    },
    {
        category: "Computer Security",
        description: "Essentials of Information Security Risk Management",
        difficulty: "Intermediate",
        duration: "5hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/7083/alison_courseware_intro_7083.jpg",
        provider: "Alison",
        title: "ISO 27005 - Essentials of Information Security Risk Management",   
        url: "https://alison.com/course/iso-27005-essentials-of-information-security-risk-management",
    },
    {
        category: "Computer Security",
        description: "Data Protection and Privacy Information Management",
        difficulty: "Intermediate",
        duration: "4hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/7041/alison_courseware_intro_7041.jpg",
        provider: "Alison",
        title: "ISO 27701 - Data Protection and Privacy Information Management",   
        url: "https://alison.com/course/iso-27701-data-protection-and-privacy-information-management",
    },
    {
        category: "Computer Security",
        description: "Cyber Security Best Practices and Standards",
        difficulty: "Intermediate",
        duration: "4hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/5532/alison_courseware_intro_5532.jpg",
        provider: "Alison",
        title: "Cyber Security Best Practices and Standards",   
        url: "https://alison.com/course/cyber-security-best-practices-and-standards",
    },
    {
        category: "Computer Security",
        description: "Ethical Hacking Introduction",
        difficulty: "Advanced",
        duration: "3hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/2276/alison_courseware_intro_2276.jpg",
        provider: "Alison",
        title: "Ethical Hacking; Information Security",   
        url: "https://alison.com/course/ethical-hacking-information-security",
    },
    {
        category: "Computer Security",
        description: "Trust and security with Google Cloud",
        difficulty: "Advanced",
        duration: "1hr",
        imageUrl: "https://www.simplilearn.com/ice9/app/Trust-and-Security-with-Google-Cloud.jpg",
        provider: "Simplilearn",
        title: "Trust and security with Google Cloud",   
        url: "https://www.simplilearn.com/free-trust-and-security-with-google-cloud-course-skillup?tag=information%20security",
    },
    {
        category: "Computer Security",
        description: "Computer Security and the Internet of Things - Risks and Challenges",
        difficulty: "Advanced",
        duration: "10hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image/dd04435a06ae.jpg",
        provider: "Class Central",
        title: "Computer Security and the Internet of Things - Risks and Challenges",   
        url: "https://www.classcentral.com/classroom/youtube-usenix-enigma-2016-computer-security-and-the-internet-of-things-165518",
    },
    {
        category: "Network Administration",
        description: "Wired and Wireless Networks and Protocols",
        difficulty: "Beginner",
        duration: "3hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/1443/alison_courseware_intro_1443.jpg",
        provider: "Alison",
        title: "Computer Networking - Wired and Wireless Networks and Protocols",   
        url: "https://alison.com/course/computer-networking-wired-and-wireless-networks-and-protocols-revised",
    },
    {
        category: "Network Administration",
        description: "Local Area Networks and the OSI Model",
        difficulty: "Beginner",
        duration: "3hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/1442/alison_courseware_intro_1442.jpg",
        provider: "Alison",
        title: "Computer Networking - Local Area Networks and the OSI Model",   
        url: "https://alison.com/course/computer-networking-local-area-networks-and-the-osi-model-revised",
    },
    {
        category: "Network Administration",
        description: "Introduction to AWS Networking",
        difficulty: "Beginner",
        duration: "1hr",
        imageUrl: "https://www.simplilearn.com/ice9/app/AWS-Networking-Basics.jpg",
        provider: "Simplilearn",
        title: "AWS Networking Basics",   
        url: "https://www.simplilearn.com/free-aws-networking-course-skillup?tag=computer%20networking",
    },
    {
        category: "Network Administration",
        description: "Fundamentals of Network Engineering",
        difficulty: "Intermediate",
        duration: "16hrs",
        imageUrl: "https://www.simplilearn.com/ice9/app/AWS-Networking-Basics.jpg",
        provider: "Udemy",
        title: "Fundamentals of Network Engineering",   
        url: "https://www.udemy.com/course/fundamentals-of-networking-for-effective-backend-design/?couponCode=ST3MT200225A",
    },
    {
        category: "Network Administration",
        description: "Cisco CCNA 200-301 - The Complete Guide to Getting Certified",
        difficulty: "Intermediate",
        duration: "42hrs",
        imageUrl: "https://www.simplilearn.com/ice9/app/AWS-Networking-Basics.jpg",
        provider: "Udemy",
        title: "Cisco CCNA 200-301 - The Complete Guide to Getting Certified",   
        url: "https://www.udemy.com/course/ccna-complete/?couponCode=ST3MT200225A",
    },
    {
        category: "Network Administration",
        description: "VMware and vSphere 6.5 Administration",
        difficulty: "Intermediate",
        duration: "15hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/3617/alison_courseware_intro_3617.jpg",
        provider: "Alison",
        title: "Diploma in VMware and vSphere 6.5 Administration",   
        url: "https://alison.com/course/diploma-in-vmware-and-vsphere-6-5-administration",
    },
    {
        category: "Network Administration",
        description: "CompTIA Cloud+ Advanced",
        difficulty: "Advanced",
        duration: "4hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/1943/alison_courseware_intro_1943.jpg",
        provider: "Alison",
        title: "CompTIA Cloud+ Advanced",   
        url: "https://alison.com/course/comptia-cloud-advanced",
    },
    {
        category: "Network Administration",
        description: "Cisco Certified Network Associate ( CCNA 200-301 ) Kursu",
        difficulty: "Advanced",
        duration: "52hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/3617/alison_courseware_intro_3617.jpg",
        provider: "Udemy",
        title: "Cisco Certified Network Associate ( CCNA 200-301 ) Kursu",   
        url: "https://www.udemy.com/course/cisco-certified-network-associate-ccna-200-301-egitimi/",
    },
    {
        category: "Network Administration",
        description: "Introduction to Connectivity Technologies and Sensor Networks",
        difficulty: "Advanced",
        duration: "6hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/2352/alison_courseware_intro_2352.jpg",
        provider: "Alison",
        title: "Introduction to Connectivity Technologies and Sensor Networks",   
        url: "https://alison.com/course/introduction-to-connectivity-technologies-and-sensor-networks",
    },
    {
        category: "Project Management",
        description: "Introduction to Jira",
        difficulty: "Beginner",
        duration: "1hr",
        imageUrl: "https://www.simplilearn.com/ice9/app/Introduction-to-JIRA.jpg",
        provider: "Simplilearn",
        title: "Introduction to Jira",   
        url: "https://www.simplilearn.com/free-jira-course-skillup?tag=project%20management",
    },
    {
        category: "Project Management",
        description: "Project Management certification training",
        difficulty: "Beginner",
        duration: "2hrs",
        imageUrl: "https://www.simplilearn.com/ice9/app/Project-Management-101-PMP-certification-training.jpg",
        provider: "Simplilearn",
        title: "Project Management 101: PMP certification training",   
        url: "https://www.simplilearn.com/free-pmp-beginner-course-skillup?tag=project%20management",
    },
    {
        category: "Project Management",
        description: "Project Management: The Basics for Success",
        difficulty: "Beginner",
        duration: "9hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/2352/alison_courseware_intro_2352.jpg",
        provider: "University of California via Coursera",
        title: "Project Management: The Basics for Success",   
        url: "https://www.classcentral.com/course/basicprojmanage-2782",
    },
    {
        category: "Project Management",
        description: "Managing project risks and changes",
        difficulty: "Intermediate",
        duration: "6hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image_variant/249a30e46ac9_w240.webp",
        provider: "University of California via Coursera",
        title: "Managing project risks and changes",   
        url: "https://www.classcentral.com/course/projectrisks-2730",
    },
    {
        category: "Project Management",
        description: "Agile project management",
        difficulty: "Intermediate",
        duration: "3hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/5661/alison_courseware_intro_5661.jpg",
        provider: "Alison",
        title: "Agile Project Management",   
        url: "https://alison.com/course/agile-project-management",
    },
    {
        category: "Project Management",
        description: "AI in project management",
        difficulty: "Intermediate",
        duration: "3hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/6746/alison_courseware_intro_6746.jpg",
        provider: "Alison",
        title: "AI in project management",   
        url: "https://alison.com/course/artificial-intelligence-in-project-management",
    },
    {
        category: "Project Management",
        description: "Production and Operation Management; Project Management",
        difficulty: "Advanced",
        duration: "5hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/2313/alison_courseware_intro_2313.jpg",
        provider: "Alison",
        title: "Production and Operation Management; Project Management",   
        url: "https://alison.com/course/production-and-operation-management-project-management",
    },
    {
        category: "Project Management",
        description: "Advanced Project Management-Measuring Project Performance",
        difficulty: "Advanced",
        duration: "2hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/6746/alison_courseware_intro_6746.jpg",
        provider: "Udemy",
        title: "Advanced Project Management-Measuring Project Performance",   
        url: "https://www.udemy.com/course/advanced-project-management-measuring-project-performance/?couponCode=ST3MT200225A",
    },
    {
        category: "Project Management",
        description: "Microsoft Project 2019 Advanced: Master MS Project",
        difficulty: "Advanced",
        duration: "8hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/6746/alison_courseware_intro_6746.jpg",
        provider: "Udemy",
        title: "Microsoft Project 2019 Advanced: Master MS Project",   
        url: "https://www.udemy.com/course/microsoft-project-2019-advanced-online-course/?couponCode=ST3MT200225A",
    },
    {
        category: "Artificial Intelligence",
        description: "Generative AI for beginners",
        difficulty: "Beginner",
        duration: "4hrs",
        imageUrl: "https://www.simplilearn.com/ice9/app/sqli.jpg",
        provider: "Udemy",
        title: "Generative AI for beginners",   
        url: "https://www.simplilearn.com/generative-ai-for-beginners-free-course-skillup?tag=AI",
    },
    {
        category: "Artificial Intelligence",
        description: "Artificial Intelligence - Current and Future Paradigms and Implications",
        difficulty: "Beginner",
        duration: "3hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image/5875f5649b3b.jpg",
        provider: "Class Central",
        title: "Artificial Intelligence - Current and Future Paradigms and Implications",   
        url: "https://www.classcentral.com/classroom/youtube-stanford-seminar-artificial-intelligence-current-and-future-paradigms-and-implications-191912",
    },
    {
        category: "Artificial Intelligence",
        description: "Introduction to Analytics and Artificial Intelligence - AI Training for Beginners",
        difficulty: "Beginner",
        duration: "8hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image/3ce9eb0761d9.jpg",
        provider: "Class Central",
        title: "Introduction to Analytics and Artificial Intelligence",   
        url: "https://www.classcentral.com/classroom/youtube-introduction-to-analytics-and-artificial-intelligence-ai-training-for-beginners-203978",
    },
    {
        category: "Artificial Intelligence",
        description: "AI Risk Management and Incident Response",
        difficulty: "Intermediate",
        duration: "3hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/6951/alison_courseware_intro_6951.jpg",
        provider: "Alison",
        title: "AI Risk Management and Incident Response",   
        url: "https://alison.com/course/ai-risk-management-and-incident-response",
    },
    {
        category: "Artificial Intelligence",
        description: "Prompt Engineering for AI Applications",
        difficulty: "Intermediate",
        duration: "3hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/6831/alison_courseware_intro_6831.jpg",
        provider: "Alison",
        title: "Prompt Engineering for AI Applications",   
        url: "https://alison.com/course/prompt-engineering-for-ai-applications",
    },
    {
        category: "Artificial Intelligence",
        description: "AI-Powered Cybersecurity Fundamentals",
        difficulty: "Intermediate",
        duration: "4hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/7295/alison_courseware_intro_7295.jpg",
        provider: "Alison",
        title: "AI-Powered Cybersecurity Fundamentals",   
        url: "https://alison.com/course/ai-powered-cybersecurity-fundamentals",
    },
    {
        category: "Artificial Intelligence",
        description: "Azure AI Agent Service (AI Foundry, Semantic Kernel SDK)",
        difficulty: "Advanced",
        duration: "7hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/7295/alison_courseware_intro_7295.jpg",
        provider: "Udemy",
        title: "Azure AI Agent Service",   
        url: "https://www.udemy.com/course/azure-ai-agent-service-ai-foundry-semantic-kernel-sdk/?couponCode=ST3MT200225A",
    },
    {
        category: "Artificial Intelligence",
        description: "Learn Hugging Face",
        difficulty: "Advanced",
        duration: "4hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/7295/alison_courseware_intro_7295.jpg",
        provider: "Udemy",
        title: "Learn Hugging Face Bootcamp",   
        url: "https://www.udemy.com/course/complete-hugging-face-bootcamp/?couponCode=ST3MT200225A",
    },
    {
        category: "Artificial Intelligence",
        description: "AI in Cybersecurity: Intrusion, Threat Hunting, and Incident Response",
        difficulty: "Advanced",
        duration: "4hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/7360/alison_courseware_intro_7360.jpg",
        provider: "Alison",
        title: "AI in Cybersecurity: Intrusion, Threat Hunting, and Incident Response",   
        url: "https://alison.com/course/ai-in-cybersecurity-intrusion-threat-hunting-and-incident-response",
    },
    {
        category: "Data Structure and Algorithms",
        description: "Introduction to Data structure",
        difficulty: "Beginner",
        duration: "4hrs",
        imageUrl: "https://cdn01.alison-static.net/courses/4343/alison_courseware_intro_4343.jpg",
        provider: "Alison",
        title: "Introduction to Data structure",   
        url: "https://alison.com/course/introduction-to-data-structures",
    },
    {
        category: "Data Structure and Algorithms",
        description: "Introduction to Sorting Algorithm",
        difficulty: "Beginner",
        duration: "3hrs",
        imageUrl: "https://www.simplilearn.com/ice9/app/IntroductiontotheSortingAlgorithms.jpg",
        provider: "Simplilearn",
        title: "Introduction to Sorting Algorithm",   
        url: "https://alison.com/course/ai-in-cybersecurity-intrusion-threat-hunting-and-incident-response",
    },
    {
        category: "Data Structure and Algorithms",
        description: "Fundamentals of Data structure in C",
        difficulty: "Beginner",
        duration: "10hrs",
        imageUrl: "https://www.simplilearn.com/ice9/app/sqli.jpg",
        provider: "Simplilearn",
        title: "Fundamentals of Data structure in C",   
        url: "https://www.simplilearn.com/fundamentals-of-data-structures-in-c-skillup?tag=data%20structures%20and%20algorithms",
    },
    {
        category: "Data Structure and Algorithms",
        description: "Data Structure and Algorithms deep dive using Java",
        difficulty: "Intermediate",
        duration: "16hrs",
        imageUrl: "https://www.simplilearn.com/ice9/app/sqli.jpg",
        provider: "Udemy",
        title: "Data Structure and Algorithms deep dive using Java",   
        url: "https://www.udemy.com/course/data-structures-and-algorithms-deep-dive-using-java/?couponCode=ST3MT200225A",
    },
    {
        category: "Data Structure and Algorithms",
        description: "Data Structure and Algorithm with Interview Questions - Comprehensive Python Guide",
        difficulty: "Intermediate",
        duration: "10hrs",
        imageUrl: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image/e474d73f0692.jpg",
        provider: "Class Central",
        title: "Data Structure and Algorithm with Interview Questions - Comprehensive Python Guide",   
        url: "https://www.classcentral.com/classroom/youtube-data-structure-and-algorithm-with-interview-questions-307114",
    },
    {
        category: "Data Structure and Algorithms",
        description: "Python for Data Structures, Algorithms, and Interviews!",
        difficulty: "Intermediate",
        duration: "17hrs",
        imageUrl: "https://www.simplilearn.com/ice9/app/sqli.jpg",
        provider: "Udemy",
        title: "Python for Data Structures, Algorithms, and Interviews!",   
        url: "https://www.udemy.com/course/python-for-data-structures-algorithms-and-interviews/?couponCode=ST3MT200225A",
    },
    {
        category: "Data Structure and Algorithms",
        description: "Data Structures and Algorithms Complete Course - CPP & JAVA",
        difficulty: "Advanced",
        duration: "82hrs",
        imageUrl: "https://www.simplilearn.com/ice9/app/sqli.jpg",
        provider: "Udemy",
        title: "Data Structures and Algorithms Complete Course - CPP & JAVA",   
        url: "https://www.udemy.com/course/data-structures-and-algorithms-complete-course-cpp-java/?couponCode=ST3MT200225Ahttps://www.udemy.com/course/python-for-data-structures-algorithms-and-interviews/?couponCode=ST3MT200225A",
    },
    {
        category: "Data Structure and Algorithms",
        description: "Data Structures, Algorithms and Design Patterns with Go",
        difficulty: "Advanced",
        duration: "10hrs",
        imageUrl: "https://www.simplilearn.com/ice9/app/sqli.jpg",
        provider: "Udemy",
        title: "Go: Data Structures, Algorithms and Design Patterns with Go",   
        url: "https://www.udemy.com/course/go-data-structures-algorithms-and-design-patterns-with-go/?couponCode=ST3MT200225A",
    },
    {
        category: "Data Structure and Algorithms",
        description: "Data Structures and Algorithms: A Complete Guide in C",
        difficulty: "Advanced",
        duration: "7hrs",
        imageUrl: "https://www.simplilearn.com/ice9/app/sqli.jpg",
        provider: "Udemy",
        title: "Data Structures and Algorithms: A Complete Guide in C",   
        url: "https://www.udemy.com/course/data-structures-and-algorithms-a-complete-guide-in-c/?couponCode=ST3MT200225A",
    },
];

const addCourses = async () => {
    try {
        for (const course of courses) {
            const docRef = await db.collection('courses').add(course);
            console.log(`Course added with ID: ${docRef.id}`);
        }
        console.log("All courses added successfully!");
    } catch (error) {
        console.error("Error adding courses: ", error);
    }
};

addCourses();